### ISSUE TITLE
[БАГ] Проблема с доступом в военблок

### ISSUE THREAD

**Issue by Viggo366** [NuPhase/issue_tracker#8]
**Описание ошибки**
Двери (отмеченные на скрине) не имеют доступа для военных (рядовых), из-за чего все проходят в военку через сральник снизу.

**Воспроизведение**
Уткнитесь мордой в дверь военблока, имея карточку рядового (она добыта абсолютно легально)

**Ожидаемое поведение**
LET ME IN!!!

**Снимки экрана**
![image](https://github.com/NuPhase/issue_tracker/assets/158742983/9ebd518e-439f-46c7-b495-f57541486458)

**Дополнительный контекст**
Нет.

**Comment by CheBuRek017** [comment]
Понял.

**Comment by CheBuRek017** [comment]
Пофиксил
